### ISSUE TITLE
Deploying EKS cluster erring out

### ISSUE THREAD

**Issue by skyisbeautiful** [awsimaya/PetAdoptions#55]
Setting the value of petsite_on_eks to true in /pet_stack/cdk.json results in following deployment (cdk deploy Services) error

10:23:14 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-Cluster                | petsite/Resource/Resource/Default
Failed to create resource. Error: Caller does not have permission to perform `iam:listAttachedRolePolicies`
at invokeUserFunction (/var/task/framework.js:85:19)
at process._tickCallback (internal/process/next_tick.js:68:7)
Remote function error: InvalidParameterException: Caller does not have permission to perform `iam:listAttachedRolePolicies`
at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)

**Comment by awsimaya** [comment]
Fixed this issue in #68
