### ISSUE TITLE
cdk deploy Services - AWSCDK-EKS-Cluster - Failed to create resource. IAM role's policy must include the `ec2:DescribeVpcs` action

### ISSUE THREAD

**Issue by amicco** [awsimaya/PetAdoptions#81]
Hello, running the workshop by myself I'm getting an error during the EKS cluster creation, any hints?

```
6:00:21 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-Cluster                | petsite5128E0B6
Failed to create resource. IAM role's policy must include the `ec2:DescribeVpcs` action

Logs: /aws/lambda/Services-awscdkawseksCluste-OnEventHandler42BEBAE0-8RXT0DMHS4UW

at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/requ

        new CustomResource (/home/ec2-user/environment/workshopfiles/PetAdoptions/cdk/pet_stack/node_modules/@aws-cdk/core/lib/custom-resource.ts:115:21)
        \_ new ClusterResource (/home/ec2-user/environment/workshopfiles/PetAdoptions/cdk/pet_stack/node_modules/@aws-cdk/aws-eks/lib/cluster-resource.ts:116:22)
        \_ new Cluster (/home/ec2-user/environment/workshopfiles/PetAdoptions/cdk/pet_stack/node_modules/@aws-cdk/aws-eks/lib/cluster.ts:492:18)
        \_ new Services (/home/ec2-user/environment/workshopfiles/PetAdoptions/cdk/pet_stack/lib/services.ts:166:29)
        \_ Object.<anonymous> (/home/ec2-user/environment/workshopfiles/PetAdoptions/cdk/pet_stack/app/pet_stack.ts:10:1)
        \_ Module._compile (internal/modules/cjs/loader.js:778:30)
        \_ Module.m._compile (/home/ec2-user/environment/workshopfiles/PetAdoptions/cdk/pet_stack/node_modules/ts-node/src/index.ts:858:23)
        \_ Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        \_ Object.require.extensions.(anonymous function) [as .ts] (/home/ec2-user/environment/workshopfiles/PetAdoptions/cdk/pet_stack/node_modules/ts-node/src/index.ts:861:12)
        \_ Module.load (internal/modules/cjs/loader.js:653:32)
        \_ tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        \_ Function.Module._load (internal/modules/cjs/loader.js:585:3)
        \_ Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
        \_ main (/home/ec2-user/environment/workshopfiles/PetAdoptions/cdk/pet_stack/node_modules/ts-node/src/bin.ts:227:14)
        \_ Object.<anonymous> (/home/ec2-user/environment/workshopfiles/PetAdoptions/cdk/pet_stack/node_modules/ts-node/src/bin.ts:513:3)
        \_ Module._compile (internal/modules/cjs/loader.js:778:30)
        \_ Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        \_ Module.load (internal/modules/cjs/loader.js:653:32)
        \_ tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        \_ Function.Module._load (internal/modules/cjs/loader.js:585:3)
        \_ Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
        \_ findNodeScript.then.existing (/home/ec2-user/.nvm/versions/node/v10.21.0/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
```
hereafter the CloudWatch log:

```
2020-07-20T18:00:20.744Z	1c94d494-a065-4b3b-bcbd-9176f8f86f43	INFO	[AWS eks 400 3.086s 0 retries] createCluster({
  resourcesVpcConfig: {
    securityGroupIds: [ 'sg-057351c3341818cb4', [length]: 1 ],
    subnetIds: [
      'subnet-0461b8f5831e8dd36',
      'subnet-0ed1388938f86e8f7',
      'subnet-01dcb73d911823d2a',
      'subnet-01822120dbc45ba9d',
      [length]: 4
    ]
  },
  roleArn: 'arn:aws:iam::*************:role/Services-petsiteRole37778FD6-1LAP5KOFFVGGB',
  name: 'PetSite',
  version: '1.16',
  clientRequestToken: '070a1919-fe0c-4f60-9025-c347258ef15d'
})

2020-07-20T18:00:20.745Z	1c94d494-a065-4b3b-bcbd-9176f8f86f43	ERROR	Invoke Error 	
{
    "errorType": "InvalidParameterException",
    "errorMessage": "IAM role's policy must include the `ec2:DescribeVpcs` action",
    "code": "InvalidParameterException",
    "message": "IAM role's policy must include the `ec2:DescribeVpcs` action",
    "time": "2020-07-20T18:00:20.743Z",
    "requestId": "bcf59679-f9c6-4af4-a89f-0275dc8b8ae0",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 24.563582864689938,
    "stack": [
        "InvalidParameterException: IAM role's policy must include the `ec2:DescribeVpcs` action",
        "    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)",
        "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)"
    ]
}
```

**Comment by awsimaya** [comment]
Based on this message, looks like you don't have enough permissions on the AWS account.

```
6:00:21 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-Cluster                | petsite5128E0B6
Failed to create resource. IAM role's policy must include the `ec2:DescribeVpcs` action
```
Login as Admin and you should be good.

If you already have admin permissions, make sure you follow this step properly -

https://observability.workshop.aws/installation/_deploy_app.html#update-kubeconfig
